### ISSUE TITLE
Actividad 8

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-8-modelo-en-webassembly-tim-mlnce#1]
[Diseño del Contrato.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-modelo-en-webassembly-tim-mlnce/files/11594257/Diseno.del.Contrato.pdf)

**Comment by MLR062998** [comment]
calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
